services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "9999:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 50M

  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native
    depends_on:
      db:
        condition: service_started
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: 0.25
          memory: 100M

  db:
    image: pgvector/pgvector:pg17-trixie
    container_name: db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 100M

volumes:
  db_data:
  caddy_data:
  caddy_config: